name: llama
model:
  pretrained_model_name_or_path: "/data/hongyuantao/data/SOLO/data/models/SOLO-7B_old"
  cache_dir: "/data/hongyuantao/data/data/lolcats" # Set this to where you want to save checkpoint weights
  return_dict: true
  load_in_8bit: false
  load_in_4bit: false
  device_map: cpu
  low_cpu_mem_usage: true
  torch_dtype: bfloat16
  attn_implementation: eager # eager  # so we can load attention weights
  rope_theta: 10000.0

attention:
  attention_type: mamba2
  attention_name: self_attn
  feature_map: softmax_dim
  feature_map_kwargs:
    eps: 1e-12
    # mlp: null  # to set
    fullspace: true
  layer_idx: null # to set
  learned_kernel: untied_head_einsum
  learned_kernel_kwargs:
    feature_dim: 64
    skip_connection: false
    bias: false
    zero_init: false
  tie_qk_kernels: false
  train_qk: false
  mamba2:
    use_D: false
    use_qknorm: false
    use_conv: false
  stage1: false
  stage2: true
  #softmax_attentions: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30]

